@echo off
cd /d %~dp0
echo Installing dependencies...
npm i express socket.io multer nanoid sanitize-html rate-limiter-flexible leo-profanity useragent geoip-lite better-sqlite3
echo Running migration (if needed)...
node migrate.js
echo Starting server...
node server.js
